// =============================================================================
// ZKSplunk — Attestation Relayer (SYSTEM Wallet / Fee Payer)
// =============================================================================
// This is a separate Node.js HTTP service that runs with elevated trust and
// holds the funded SYSTEM wallet. Operators (collectors) post proven-but-
// unbalanced transactions here; the relayer pays the DUST fee and submits.
//
// On-chain privacy model:
//   - The ZK proof embedded in the incoming tx was generated by the operator
//     and proves Merkle membership + nullifier uniqueness without revealing
//     which operator is attesting.
//   - This relayer adds DUST fee inputs from the SYSTEM wallet, then calls
//     wallet.balanceUnboundTransaction → normalized finalize → submitTransaction.
//   - On-chain: public sees the SYSTEM wallet's dust address paid fees.
//     The operator's Zswap coinPublicKey may appear in shielded output
//     encryption, but is derived from OPERATOR_ZSWAP_SEED (a key that holds
//     no identity-linked funds — use a fresh seed per operator for maximum
//     unlinkability).
//   - The relayer endpoint IS a de-anonymization risk for the off-chain path:
//     the relayer sees the sender's IP address and the incident metadata.
//     Layer mTLS / VPN / onion routing on the network path to the relayer
//     if strong off-chain anonymity is required. The relayer's auth/rate-limit
//     logic (see OFF-CHAIN AUTH GATE below) must NOT write anything
//     operator-identifying to the on-chain submission.
//
// Env vars required (on the RELAYER host):
//   RELAYER_WALLET_SEED         — 64-char hex seed for the SYSTEM wallet
//                                 (FUNDED with NIGHT → DUST, never share)
//   RELAYER_PORT                — HTTP port (default 7300)
//   MIDNIGHT_INDEXER_URL        — https://…/api/v4/graphql
//   MIDNIGHT_NODE_URL           — ws(s)://host:port
//   MIDNIGHT_NETWORK_ID         — 'preview' | 'undeployed'
//   MIDNIGHT_PROOF_SERVER_URL   — http(s)://host:port (needed for WalletFacade)
//   RELAYER_MAX_REQUESTS_PER_MIN  — rate-limit per source (default 6)
//   RELAYER_ALLOWED_INCIDENT_CLASSES — comma-separated allowlist (default: all)
//
// Usage:
//   npm run relayer
// =============================================================================

import WebSocket from 'ws';
(globalThis as any).WebSocket = WebSocket;

import { createServer, IncomingMessage, ServerResponse } from 'node:http';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { firstValueFrom } from 'rxjs';

import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
import { WalletFacade, WalletEntrySchema } from '@midnight-ntwrk/wallet-sdk-facade';
import type { DefaultConfiguration } from '@midnight-ntwrk/wallet-sdk-facade';
import { HDWallet, Roles } from '@midnight-ntwrk/wallet-sdk-hd';
import { ShieldedWallet } from '@midnight-ntwrk/wallet-sdk-shielded';
import {
  UnshieldedWallet,
  createKeystore,
  PublicKey as UnshieldedPublicKey,
} from '@midnight-ntwrk/wallet-sdk-unshielded-wallet';
import { DustWallet } from '@midnight-ntwrk/wallet-sdk-dust-wallet';
import { InMemoryTransactionHistoryStorage } from '@midnight-ntwrk/wallet-sdk-abstractions';
import * as ledger from '@midnight-ntwrk/ledger-v8';

import { loadConfigFromEnvironment } from '../../connector/src/config.ts';
import { SplunkHecClient } from '../../connector/src/hec-client.ts';
import { balanceAndFinalizeUnboundTransactionNormalized } from './normalized-transaction.ts';

// ---------------------------------------------------------------------------
// Load .env / .env.zkmonitor (reuse same loader as index.ts)
// ---------------------------------------------------------------------------

const HERE = dirname(fileURLToPath(import.meta.url));

function hydrateEnv(): void {
  for (const file of ['.env', '.env.zkmonitor']) {
    try {
      const raw = readFileSync(resolve(HERE, '..', file), 'utf8');
      for (const line of raw.split('\n')) {
        const t = line.trim();
        if (!t || t.startsWith('#')) continue;
        const eq = t.indexOf('=');
        if (eq === -1) continue;
        const key = t.slice(0, eq).trim();
        if (process.env[key] === undefined) process.env[key] = t.slice(eq + 1).trim();
      }
    } catch { /* file missing is fine */ }
  }
}

hydrateEnv();

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const RELAYER_WALLET_SEED = process.env.RELAYER_WALLET_SEED?.trim() || '';
const RELAYER_PORT = parseInt(process.env.RELAYER_PORT ?? '7300', 10);
const MIDNIGHT_INDEXER_URL = process.env.MIDNIGHT_INDEXER_URL ?? 'http://localhost:8088/api/v4/graphql';
const MIDNIGHT_NODE_URL = (process.env.MIDNIGHT_NODE_URL ?? 'ws://localhost:9944')
  .replace(/^http:\/\//, 'ws://')
  .replace(/^https:\/\//, 'wss://')
  .replace(/\/health$/, '');
const MIDNIGHT_NETWORK_ID = process.env.MIDNIGHT_NETWORK_ID ?? 'preview';
const MIDNIGHT_PROOF_SERVER_URL = process.env.MIDNIGHT_PROOF_SERVER_URL ?? 'http://localhost:6300';
const MAX_REQUESTS_PER_MIN = parseInt(process.env.RELAYER_MAX_REQUESTS_PER_MIN ?? '6', 10);
const ALLOWED_CLASSES_ENV = process.env.RELAYER_ALLOWED_INCIDENT_CLASSES?.trim();
const ALLOWED_INCIDENT_CLASSES: Set<string> | null = ALLOWED_CLASSES_ENV
  ? new Set(ALLOWED_CLASSES_ENV.split(',').map((s) => s.trim()))
  : null; // null = allow all

function deriveWsUrl(httpUrl: string): string {
  return httpUrl.replace(/^https/, 'wss').replace(/^http/, 'ws').replace(/\/+$/, '') + '/ws';
}

const INDEXER_WS_URL = deriveWsUrl(MIDNIGHT_INDEXER_URL);

// ---------------------------------------------------------------------------
// Splunk HEC telemetry — the relayer reports its OWN operational health so the
// attestation funnel is visible in Splunk (the "zkZap Attestation" dashboard).
//
// PRIVACY: these events carry ONLY public/aggregate data — incident class &
// severity (already public on-chain), tx hash, latency, outcome, and counts.
// They NEVER include the sender IP, operator identity, or any linking field.
// The off-chain auth gate's IP knowledge stays in memory/logs, never in Splunk.
// In a multi-operator deployment these land in the SYSTEM's Splunk (the relayer
// operator's), describing relayer health — not any individual operator.
// ---------------------------------------------------------------------------

const RELAYER_SOURCETYPE = 'zksplunk:relayer';
const _hecConfig = loadConfigFromEnvironment();
const hec: SplunkHecClient | null =
  _hecConfig.splunkHecUrl && _hecConfig.splunkHecToken
    ? new SplunkHecClient(_hecConfig)
    : null;

const relayerStats = { received: 0, submitted: 0, failed: 0, denied: 0 };
const relayerStartedAt = Date.now();
let heartbeatTimer: ReturnType<typeof setInterval> | null = null;

/** Emit a relayer telemetry event to Splunk (no-op if HEC is not configured). */
function emitRelayer(type: string, fields: Record<string, any> = {}): void {
  if (!hec) return;
  hec.enqueue({
    sourcetype: RELAYER_SOURCETYPE,
    source: 'zksplunk-relayer',
    event: { type, network_id: MIDNIGHT_NETWORK_ID, ...fields },
  });
}

/** Coarse error category for the dashboard, derived from the error message. */
function classifyRelayError(msg: string): string {
  const m = msg.toLowerCase();
  if (m.includes('deserial')) return 'deserialize';
  if (m.includes('balance') || m.includes('dust') || m.includes('fund') || m.includes('fee')) return 'balance';
  if (m.includes('merge')) return 'merge';
  if (m.includes('submit') || m.includes('node')) return 'submit';
  if (m.includes('proof') || m.includes('verif')) return 'proof';
  return 'other';
}

// ---------------------------------------------------------------------------
// OFF-CHAIN AUTH GATE (STUB)
// ---------------------------------------------------------------------------
// This function is called before we touch the transaction. It receives the
// sender's IP and the metadata the operator sent.
//
// CRITICAL PRIVACY NOTE: any identity information checked here (IP, API key,
// operator ID) exists ONLY in this function's memory and must NOT be included
// in the transaction or passed on-chain in any form. The on-chain submission
// is anonymous — this gate only controls whether we proceed.
//
// IMPLEMENT: replace this stub with real logic appropriate for your threat
// model. Options include:
//   - IP-based rate limiting (already stubbed below)
//   - Pre-shared API keys per collector (Bearer token in Authorization header)
//   - mTLS client certificate verification (enforce at the TLS layer)
//   - Collector registry (registered operator Zswap pubkeys, checked off-chain)
// ---------------------------------------------------------------------------

interface AttestMeta {
  incidentClass?: string;
  severity?: string;
  epoch?: string;
}

// In-memory rate-limit counters keyed by source IP.
// Production: replace with Redis or a sliding-window implementation.
const rateLimitCounters = new Map<string, { count: number; windowStart: number }>();

function checkOffChainAuthGate(
  sourceIp: string,
  meta: AttestMeta,
): { allowed: boolean; reason?: string } {
  // 1. Incident class allowlist (if configured).
  if (ALLOWED_INCIDENT_CLASSES && meta.incidentClass) {
    if (!ALLOWED_INCIDENT_CLASSES.has(meta.incidentClass)) {
      return { allowed: false, reason: `incident class '${meta.incidentClass}' not in allowlist` };
    }
  }

  // 2. Per-IP rate limit: MAX_REQUESTS_PER_MIN per sliding 60-second window.
  //    STUB — this uses in-process memory; use Redis for multi-instance deployments.
  const now = Date.now();
  const entry = rateLimitCounters.get(sourceIp) ?? { count: 0, windowStart: now };
  if (now - entry.windowStart > 60_000) {
    // Window expired — reset.
    entry.count = 0;
    entry.windowStart = now;
  }
  entry.count++;
  rateLimitCounters.set(sourceIp, entry);
  if (entry.count > MAX_REQUESTS_PER_MIN) {
    return { allowed: false, reason: `rate limit exceeded (${entry.count}/${MAX_REQUESTS_PER_MIN} per min)` };
  }

  // 3. TODO: add mTLS / API key check here.
  //    Example:
  //    const apiKey = request.headers['x-relayer-key'];
  //    if (apiKey !== KNOWN_COLLECTOR_KEYS.get(sourceIp)) {
  //      return { allowed: false, reason: 'invalid API key' };
  //    }

  return { allowed: true };
}

// ---------------------------------------------------------------------------
// Relayer wallet init
// ---------------------------------------------------------------------------

interface RelayerWallet {
  wallet: WalletFacade;
  shieldedSecretKeys: ledger.ZswapSecretKeys;
  dustSecretKey: ledger.DustSecretKey;
}

async function initRelayerWallet(): Promise<RelayerWallet> {
  if (!RELAYER_WALLET_SEED) {
    throw new Error(
      'RELAYER_WALLET_SEED is not set. The relayer requires a funded SYSTEM wallet ' +
        '(NIGHT → DUST). Set this env var before starting the relayer.',
    );
  }

  setNetworkId(MIDNIGHT_NETWORK_ID);

  const seedBytes = Buffer.from(RELAYER_WALLET_SEED.replace(/^0x/, ''), 'hex');
  const walletResult = HDWallet.fromSeed(seedBytes);
  if (walletResult.type !== 'seedOk') {
    throw new Error(`Invalid RELAYER_WALLET_SEED: ${String(walletResult)}`);
  }

  const derivationResult = walletResult.hdWallet
    .selectAccount(0)
    .selectRoles([Roles.Zswap, Roles.NightExternal, Roles.Dust] as const)
    .deriveKeysAt(0);

  walletResult.hdWallet.clear();

  if (derivationResult.type !== 'keysDerived') {
    throw new Error('HD key derivation failed for RELAYER_WALLET_SEED: keyOutOfBounds');
  }

  const shieldedSecretKeys = ledger.ZswapSecretKeys.fromSeed(derivationResult.keys[Roles.Zswap]);
  const dustSecretKey = ledger.DustSecretKey.fromSeed(derivationResult.keys[Roles.Dust]);
  const unshieldedKeystore = createKeystore(
    derivationResult.keys[Roles.NightExternal],
    MIDNIGHT_NETWORK_ID,
  );

  const walletConfig: DefaultConfiguration = {
    networkId: MIDNIGHT_NETWORK_ID,
    costParameters: { feeBlocksMargin: 5 },
    relayURL: new URL(MIDNIGHT_NODE_URL),
    provingServerUrl: new URL(MIDNIGHT_PROOF_SERVER_URL),
    indexerClientConnection: {
      indexerHttpUrl: MIDNIGHT_INDEXER_URL,
      indexerWsUrl: INDEXER_WS_URL,
    },
    txHistoryStorage: new InMemoryTransactionHistoryStorage(WalletEntrySchema),
  };

  const wallet = await WalletFacade.init({
    configuration: walletConfig,
    shielded: (c) => ShieldedWallet(c).startWithSecretKeys(shieldedSecretKeys),
    unshielded: (c) =>
      UnshieldedWallet(c).startWithPublicKey(UnshieldedPublicKey.fromKeyStore(unshieldedKeystore)),
    dust: (c) =>
      DustWallet(c).startWithSecretKey(
        dustSecretKey,
        ledger.LedgerParameters.initialParameters().dust,
      ),
  });

  await wallet.start(shieldedSecretKeys, dustSecretKey);

  const facadeState = await firstValueFrom(wallet.state());
  const unshieldedState = facadeState.unshielded;

  // eslint-disable-next-line no-console
  console.log(
    `[relayer] SYSTEM wallet initialized\n` +
      `  network     : ${MIDNIGHT_NETWORK_ID}\n` +
      `  unshielded  : ${JSON.stringify(unshieldedState)}\n` +
      `  dust balance: ${JSON.stringify(facadeState.dust)}`,
  );

  return { wallet, shieldedSecretKeys, dustSecretKey };
}

// ---------------------------------------------------------------------------
// Core relay logic
// ---------------------------------------------------------------------------
// RELAYER SIDE FLOW:
//   1. Deserialize the operator's proven-but-unbalanced UnboundTransaction.
//      Type: Transaction<SignatureEnabled, Proof, PreBinding>
//      Deserialize markers: 'signature', 'proof', 'pre-binding'
//
//   2. wallet.balanceUnboundTransaction(tx, secretKeys, { ttl }) →
//      UnboundTransactionRecipe
//      This creates a companion balancing transaction (pure DUST spend,
//      no contract calls) that covers the fee. The relayer's dustSecretKey
//      authorizes spending the DUST. Merge constraint is satisfied because
//      the balancing tx has no contract interactions.
//
//   3. normalized finalize → FinalizedTransaction
//      Merges fee first and operator contract call second. This avoids
//      InvalidTransaction::Custom(117) / NotNormalized on preview nodes.
//
//   4. wallet.submitTransaction(finalTx) → txHash
// ---------------------------------------------------------------------------

async function relayAttestation(
  relayerWallet: RelayerWallet,
  provenTxBase64: string,
): Promise<{ txHash: string; blockHeight: number | null }> {
  const { wallet, shieldedSecretKeys, dustSecretKey } = relayerWallet;

  // Step 1: Deserialize the proven-but-unbalanced transaction.
  // Transaction.deserialize takes string literal markers, not class instances.
  // UnboundTransaction = Transaction<SignatureEnabled, Proof, PreBinding>
  const rawBytes = Buffer.from(provenTxBase64, 'base64');
  const unboundTx = ledger.Transaction.deserialize(
    'signature' as 'signature',   // markerS: SignatureEnabled['instance']
    'proof' as 'proof',           // markerP: Proof['instance']
    'pre-binding' as 'pre-binding', // markerB: PreBinding['instance']
    rawBytes,
  ) as ledger.Transaction<ledger.SignatureEnabled, ledger.Proof, ledger.PreBinding>;

  // Step 2: Balance — relayer adds DUST fee inputs (no contract calls in
  // the balancing transaction, so Transaction.merge constraint is satisfied).
  const ttl = new Date(Date.now() + 30 * 60 * 1000); // 30 min from now
  const finalTx = await balanceAndFinalizeUnboundTransactionNormalized(
    wallet,
    unboundTx as any,
    { shieldedSecretKeys, dustSecretKey },
    { ttl },
  );

  // Step 4: Submit to the Midnight network.
  const txId = await wallet.submitTransaction(finalTx);

  // eslint-disable-next-line no-console
  console.log(`[relayer] submitted attestation tx: ${txId}`);

  // blockHeight is not available synchronously from submitTransaction.
  // Return txId as txHash; blockHeight must be confirmed via indexer separately.
  // LIVE NETWORK NOTE: txId is the transaction hash on Midnight.
  return { txHash: txId, blockHeight: null };
}

// ---------------------------------------------------------------------------
// HTTP server
// ---------------------------------------------------------------------------

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on('data', (chunk: Buffer) => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

function getSourceIp(req: IncomingMessage): string {
  const forwarded = req.headers['x-forwarded-for'];
  if (forwarded) {
    return (Array.isArray(forwarded) ? forwarded[0] : forwarded).split(',')[0].trim();
  }
  return req.socket.remoteAddress ?? 'unknown';
}

function sendJson(res: ServerResponse, status: number, data: unknown): void {
  const body = JSON.stringify(data);
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(body),
  });
  res.end(body);
}

async function main() {
  if (!RELAYER_WALLET_SEED) {
    // eslint-disable-next-line no-console
    console.error('[relayer] RELAYER_WALLET_SEED is not set. Exiting.');
    process.exit(1);
  }

  let relayerWallet: RelayerWallet;
  try {
    relayerWallet = await initRelayerWallet();
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('[relayer] Wallet initialization failed:', (err as Error).message);
    process.exit(1);
  }

  const server = createServer(async (req, res) => {
    // Health check.
    if (req.method === 'GET' && req.url === '/health') {
      sendJson(res, 200, { status: 'ok' });
      return;
    }

    // Attestation relay endpoint.
    if (req.method === 'POST' && req.url === '/attest') {
      const sourceIp = getSourceIp(req);

      let body: { provenTxBase64?: string; meta?: AttestMeta };
      try {
        const raw = await readBody(req);
        body = JSON.parse(raw) as typeof body;
      } catch {
        sendJson(res, 400, { error: 'Invalid JSON body' });
        return;
      }

      if (!body.provenTxBase64) {
        sendJson(res, 400, { error: 'Missing provenTxBase64' });
        return;
      }

      // Public/aggregate fields only — class & severity are public on-chain.
      const incidentClass = body.meta?.incidentClass ?? null;
      const severity = body.meta?.severity ?? null;
      relayerStats.received += 1;
      emitRelayer('zksplunk.relayer.received', { incident_class: incidentClass, severity });

      // OFF-CHAIN AUTH GATE — checked before touching the transaction.
      // This gate learns the sender's IP + meta. That information STAYS HERE.
      // It is never included in the on-chain transaction OR in Splunk telemetry.
      const gate = checkOffChainAuthGate(sourceIp, body.meta ?? {});
      if (!gate.allowed) {
        // eslint-disable-next-line no-console
        console.warn(`[relayer] rejected from ${sourceIp}: ${gate.reason}`);
        relayerStats.denied += 1;
        // NOTE: gate.reason is safe (rate_limited / class-not-allowed); never the IP.
        emitRelayer('zksplunk.relayer.denied', { reason: gate.reason, incident_class: incidentClass });
        sendJson(res, 429, { error: `Request rejected: ${gate.reason}` });
        return;
      }

      const t0 = Date.now();
      try {
        const result = await relayAttestation(relayerWallet, body.provenTxBase64);
        relayerStats.submitted += 1;
        emitRelayer('zksplunk.relayer.submitted', {
          incident_class: incidentClass,
          severity,
          tx_hash: result.txHash,
          block_height: result.blockHeight,
          latency_ms: Date.now() - t0,
        });
        sendJson(res, 200, result);
      } catch (err) {
        const msg = (err as Error).message ?? String(err);
        // eslint-disable-next-line no-console
        console.error(`[relayer] relay error from ${sourceIp}:`, msg);
        relayerStats.failed += 1;
        emitRelayer('zksplunk.relayer.failed', {
          incident_class: incidentClass,
          severity,
          error_category: classifyRelayError(msg),
          latency_ms: Date.now() - t0,
        });
        sendJson(res, 500, { error: `Relay failed: ${msg}` });
      }
      return;
    }

    sendJson(res, 404, { error: 'Not found' });
  });

  server.listen(RELAYER_PORT, () => {
    // eslint-disable-next-line no-console
    console.log(
      `[relayer] Attestation relayer listening on port ${RELAYER_PORT}\n` +
        `  network     : ${MIDNIGHT_NETWORK_ID}\n` +
        `  indexer     : ${MIDNIGHT_INDEXER_URL}\n` +
        `  rate limit  : ${MAX_REQUESTS_PER_MIN} req/min per source IP\n` +
        `  splunk hec  : ${hec ? 'on (zksplunk:relayer)' : 'off (no HEC config)'}`,
    );
    emitRelayer('zksplunk.relayer.started', {
      port: RELAYER_PORT,
      wallet_ready: true,
      rate_limit_per_min: MAX_REQUESTS_PER_MIN,
    });
  });

  // Periodic heartbeat so the dashboard can show relayer liveness + running totals.
  heartbeatTimer = setInterval(() => {
    emitRelayer('zksplunk.relayer.heartbeat', {
      uptime_seconds: Math.round((Date.now() - relayerStartedAt) / 1000),
      total_received: relayerStats.received,
      total_submitted: relayerStats.submitted,
      total_failed: relayerStats.failed,
      total_denied: relayerStats.denied,
    });
  }, 30_000);

  const shutdown = async () => {
    // eslint-disable-next-line no-console
    console.log('\n[relayer] Shutting down…');
    if (heartbeatTimer) clearInterval(heartbeatTimer);
    server.close();
    if (hec) await hec.shutdown();
    await relayerWallet.wallet.stop();
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('[relayer] Fatal error:', err);
  process.exit(1);
});
